modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="simplemap"
version="0.1.0-SNAPSHOT"
displayName="Simple Map Continuum"
description='''Continuously maintained cross-loader map core'''
[[dependencies.simplemap]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.simplemap]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
